name: firebase_ml_vision_example
description: Demonstrates how to use the firebase_ml_vision plugin.
author: Flutter Team <flutter-dev@googlegroups.com>
version: 0.1.1

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.6.7+12
  cupertino_icons: ^0.1.2
  firebase_ml_vision: 0.9.8
  camera: ^0.5.8+11
  exif:
  file_picker:
  image:
  path_provider: ^1.6.11

  http: ^0.12.2


dev_dependencies:
  pedantic: ^1.8.0
  e2e: ^0.6.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  path: ^1.6.2

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/icons/android-icon-192x192.png"
  image_path_ios: "assets/icons/apple-icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:
  uses-material-design: true
  assets:
    - assets/sortedIngredients.json
